---
- name: "Common | Update all packages to their latest version"  # noqa package-latest
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

- name: "Common | Packages installation"
  ansible.builtin.apt:
    pkg:
      - "apt-transport-https"
      - "build-essential"
      - "ca-certificates"
      - "ccze"
      - "cloud-init"
      - "curl"
      - "debian-goodies"
      - "dfc"
      - "git"
      - "gnupg"
      - "gnupg-agent"
      - "htop"
      - "ifstat"
      - "jq"
      - "libsystemd-dev"
      - "lsb-release"
      - "lsof"
      - "lvm2"
      - "make"
      - "ncdu"
      - "net-tools"
      - "parted"
      - "pkg-config"
      - "python3"
      - "python3-docker"
      - "python3-pip"
      - "python3-psutil"
      - "python3-software-properties"
      - "python3-yaml"
      - "rng-tools"
      - "screen"
      - "software-properties-common"
      - "ssh"
      - "sysstat"
      - "tree"
      - "ufw"
      - "unattended-upgrades"
      - "unzip"
      - "vim"
      - "zip"
    state: present
    update_cache: true
    install_recommends: false
    cache_valid_time: 300

- name: "Common | Remove insecure legacy packages if they are still present"
  ansible.builtin.apt:
    pkg:
      - xinetd
      - nis
      - yp-tools
      - tftpd
      - atftpd
      - tftpd-hpa
      - telnetd
      - rsh-server
      - rsh-redone-server
    state: absent
    purge: true

- name: "Common | Install varnishgather"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/varnish/varnishgather/master/varnishgather"
    dest: "/usr/local/bin/varnishgather"
    mode: "0755"
    owner: root
    group: root

- name: "Common | Set timezone to {{ common_timezone }}"
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: "Common | Make vim the default editor"
  community.general.alternatives:
    name: editor
    path: "/usr/bin/vim.basic"

- name: "Common | Set limits.conf"
  ansible.builtin.copy:
    src: "limits.conf"
    dest: "/etc/security/limits.conf"
    mode: "0644"
    owner: "root"
    group: "root"

- name: "Common | Create directory /etc/varnish_software"
  ansible.builtin.file:
    path: "/etc/varnish_software"
    state: directory
    mode: "0750"
    owner: "root"
    group: "root"

- name: "Common | Copy journald.conf configuration template to /etc/systemd"
  ansible.builtin.copy:
    src: "journald.conf"
    dest: "/etc/systemd/journald.conf"
    mode: "0644"
    owner: root
    group: root
  notify: "Restart journald"

- name: "Common | Copy rsyslog rotate config file to /etc/logrotate.d/"
  ansible.builtin.copy:
    src: "rsyslog"
    dest: "/etc/logrotate.d/rsyslog"
    mode: "0644"
    owner: root
    group: root
  notify: "Restart rsyslog"

- name: "Common | Set vm.swappiness default"
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    reload: true

- name: "Common | Restart systemd-journald"
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    enabled: true
    daemon_reload: true
